exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('states')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('states').insert([
        { postal_code: 'AL', name: 'Alabama', tax_rate: 0.04 },
        { postal_code: 'AK', name: 'Alaska', tax_rate: 0.0 },
        { postal_code: 'AZ', name: 'Arizona', tax_rate: 0.056 },
        { postal_code: 'AR', name: 'Arkansas', tax_rate: 0.065 },
        { postal_code: 'CA', name: 'California', tax_rate: 0.0725 },
        { postal_code: 'CO', name: 'Colorado', tax_rate: 0.029 },
        { postal_code: 'CT', name: 'Connecticut', tax_rate: 0.0635 },
        { postal_code: 'DE', name: 'Deleware', tax_rate: 0.0 },
        { postal_code: 'DC', name: 'District of Columbia', tax_rate: 0.06 },
        { postal_code: 'FL', name: 'Florida', tax_rate: 0.06 },
        { postal_code: 'GA', name: 'Georgia', tax_rate: 0.04 },
        { postal_code: 'HI', name: 'Hawaii', tax_rate: 0.04 },
        { postal_code: 'ID', name: 'Idaho', tax_rate: 0.06 },
        { postal_code: 'IL', name: 'Illinois', tax_rate: 0.0625 },
        { postal_code: 'IN', name: 'Indiana', tax_rate: 0.07 },
        { postal_code: 'IA', name: 'Iowa', tax_rate: 0.06 },
        { postal_code: 'KS', name: 'Kansas', tax_rate: 0.065 },
        { postal_code: 'KY', name: 'Kentucky', tax_rate: 0.06 },
        { postal_code: 'LA', name: 'Louisiana', tax_rate: 0.0445 },
        { postal_code: 'ME', name: 'Maine', tax_rate: 0.055 },
        { postal_code: 'MD', name: 'Maryland', tax_rate: 0.06 },
        { postal_code: 'MA', name: 'Massachusetts', tax_rate: 0.0625 },
        { postal_code: 'MI', name: 'Michigan', tax_rate: 0.06 },
        { postal_code: 'MN', name: 'Minnesota', tax_rate: 0.06875 },
        { postal_code: 'MS', name: 'Mississippi', tax_rate: 0.07 },
        { postal_code: 'MO', name: 'Missouri', tax_rate: 0.04225 },
        { postal_code: 'MT', name: 'Montana', tax_rate: 0.0 },
        { postal_code: 'NE', name: 'Nebraska', tax_rate: 0.055 },
        { postal_code: 'NV', name: 'Nevada', tax_rate: 0.0685 },
        { postal_code: 'NH', name: 'New Hampshire', tax_rate: 0.0 },
        { postal_code: 'NJ', name: 'New Jersey', tax_rate: 0.06625 },
        { postal_code: 'NM', name: 'New Mexico', tax_rate: 0.05125 },
        { postal_code: 'NY', name: 'New York', tax_rate: 0.04 },
        { postal_code: 'NC', name: 'North Carolina', tax_rate: 0.0475 },
        { postal_code: 'ND', name: 'North Dakota', tax_rate: 0.05 },
        { postal_code: 'OH', name: 'Ohio', tax_rate: 0.0575 },
        { postal_code: 'OK', name: 'Oklahoma', tax_rate: 0.045 },
        { postal_code: 'OR', name: 'Oregon', tax_rate: 0.0 },
        { postal_code: 'PA', name: 'Pennsylvania', tax_rate: 0.06 },
        { postal_code: 'RI', name: 'Rhode Island', tax_rate: 0.07 },
        { postal_code: 'SC', name: 'South Carolina', tax_rate: 0.06 },
        { postal_code: 'SD', name: 'South Dakota', tax_rate: 0.045 },
        { postal_code: 'TN', name: 'Tennessee', tax_rate: 0.07 },
        { postal_code: 'TX', name: 'Texas', tax_rate: 0.0625 },
        { postal_code: 'UT', name: 'Utah', tax_rate: 0.0485 },
        { postal_code: 'VT', name: 'Vermont', tax_rate: 0.06 },
        { postal_code: 'VA', name: 'Virginia', tax_rate: 0.043 },
        { postal_code: 'WA', name: 'Washington', tax_rate: 0.065 },
        { postal_code: 'WV', name: 'West Virginia', tax_rate: 0.06 },
        { postal_code: 'WI', name: 'Wisconsin', tax_rate: 0.05 },
        { postal_code: 'WY', name: 'Wyoming', tax_rate: 0.04 },
      ]);
    });
};
