exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('payment_cards')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('payment_cards').insert([
        {
          primary: true,
          card_name: 'Jack Sparrow',
          card_number: '1111-1111-1111-1111',
          expiration: '12/20',
          cvv: '123',
          street: '321 Easy Street',
          apt_suite: '',
          city: 'New York City',
          state_id: 33,
          country: 'USA',
          zip: '12345',
          user_id: 1,
        },
        {
          primary: false,
          card_name: 'Jack Sparrow',
          card_number: '3333-3333-3333-3333',
          expiration: '10/20',
          cvv: '789',
          street: '1428 Elm Street',
          apt_suite: '',
          city: 'Chicago',
          state_id: 14,
          country: 'USA',
          zip: '12345',
          user_id: 1,
        },
        {
          primary: true,
          card_name: 'Hector Barbosa',
          card_number: '2222-2222-2222-2222',
          expiration: '11/20',
          cvv: '456',
          street: '1155 Buckey Road',
          apt_suite: '',
          city: 'Los Angeles',
          state_id: 5,
          country: 'USA',
          zip: '12345',
          user_id: 2,
        },
        {
          primary: true,
          card_name: 'Godzilla',
          card_number: '4444-4444-4444-4444',
          expiration: '9/20',
          cvv: '012',
          street: '307A Kamani Street',
          apt_suite: '',
          city: 'Houston',
          state_id: 44,
          country: 'USA',
          zip: '12345',
          user_id: 4,
        },
        {
          primary: true,
          card_name: 'Sega Sanshiro',
          card_number: '5555-5555-5555-5555',
          expiration: '8/20',
          cvv: '345',
          street: '1630 Liholiho Street',
          apt_suite: '',
          city: 'Philadelphia',
          state_id: 39,
          country: 'USA',
          zip: '12345',
          user_id: 5,
        },
        {
          primary: true,
          card_name: 'Chuck Norris',
          card_number: '6666-6666-6666-6666',
          expiration: '7/20',
          cvv: '678',
          street: '123 Sesame Street',
          apt_suite: '',
          city: 'Pheonix',
          state_id: 3,
          country: 'USA',
          zip: '12345',
          user_id: 6,
        },
      ]);
    });
};
