exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('items')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('items').insert([
        {
          user_id: 1,
          active: true,
          condition_id: 1,
          category_id: 1,
          sub_category_id: 1,
          name: 'Insignia - 55" Class - LED - Smart - 4K UHD TV with HDR - Fire TV Edition',
          inventory: 1,
          dimensions: '55 inches',
          view_count: 170,
          price: 339.0,
          shipping_cost: 12.99,
          description: 'kick ass 55 inch tv bruh',
          approved: true,
        },
        {
          user_id: 1,
          active: true,
          condition_id: 2,
          category_id: 1,
          sub_category_id: 1,
          name: 'LG - 70" Class - LED - UK6190 Series - 2160p - Smart -4K UHD TV with HDR',
          inventory: 2,
          dimensions: '70 inches',
          view_count: 170,
          price: 523.0,
          shipping_cost: 12.99,
          description: 'ho cuz got one kick ass 70 inch tv cuz',
          approved: false,
        },
        {
          user_id: 2,
          active: true,
          condition_id: 3,
          category_id: 1,
          sub_category_id: 2,
          name: 'LG - Stylo 4 with 32GB Memory',
          inventory: 3,
          dimensions: '6.2"',
          view_count: 88,
          price: 149.99,
          shipping_cost: 4.99,
          description: 'Black phone with stylus',
          approved: true,
        },
        {
          user_id: 2,
          active: true,
          condition_id: 4,
          category_id: 1,
          sub_category_id: 2,
          name: 'Moto G6 - 32GB Black',
          inventory: 900,
          dimensions: '5.7"',
          view_count: 96,
          price: 179.99,
          shipping_cost: 4.99,
          description: 'lightly damaged but still works',
          approved: false,
        },
        {
          user_id: 3,
          active: true,
          condition_id: 5,
          category_id: 2,
          sub_category_id: 3,
          name: "Skechers Men's Go Walk Evolution Ultra-Impeccable Sneaker",
          inventory: 4,
          dimensions: 'Size 7',
          view_count: 17,
          price: 17.17,
          shipping_cost: 7.99,
          description: 'These shoes make you go faster!',
          approved: true,
        },
        {
          user_id: 3,
          active: false,
          condition_id: 1,
          category_id: 2,
          sub_category_id: 3,
          name: 'Adidas Womens Questar Slide',
          inventory: 1,
          dimensions: 'Size 5',
          view_count: 909,
          price: 32.91,
          shipping_cost: 7.99,
          description: 'flippy flops',
          approved: false,
        },
        {
          user_id: 4,
          active: true,
          condition_id: 1,
          category_id: 2,
          sub_category_id: 4,
          name: 'KAVU Womens Woodland Parka',
          inventory: 2,
          dimensions: 'Medium',
          view_count: 88,
          price: 12.22,
          shipping_cost: 5.99,
          description: 'You will look good in this',
          approved: true,
        },
        {
          user_id: 4,
          active: true,
          condition_id: 2,
          category_id: 2,
          sub_category_id: 4,
          name: 'Jerzees Mens Spot Shield Short Sleeve Polo Sport Shirt',
          inventory: 4,
          dimensions: 'Large',
          view_count: 17,
          price: 4.86,
          shipping_cost: 5.99,
          description: 'This shirt got me laid',
          approved: false,
        },
        {
          user_id: 5,
          active: true,
          condition_id: 3,
          category_id: 3,
          sub_category_id: 5,
          name: 'The Dread Hammer',
          inventory: 10,
          dimensions: '589 pages',
          view_count: 17,
          price: 12.0,
          shipping_cost: 3.99,
          description: 'A lifechanging story',
          approved: true,
        },
        {
          // item #10
          user_id: 5,
          active: true,
          condition_id: 4,
          category_id: 3,
          sub_category_id: 5,
          name: 'Light and Shadows: Eight Short Stories',
          inventory: 1,
          dimensions: '600 pages',
          view_count: 17,
          price: 10.0,
          shipping_cost: 3.99,
          description: 'Visit high-tech battlefields, surreal other worlds, an orbital habitat, and a distant moon.',
          approved: false,
        },
        {
          user_id: 6,
          active: false,
          condition_id: 5,
          category_id: 3,
          sub_category_id: 6,
          name: 'Thin Air',
          inventory: 1,
          dimensions: '543 pages',
          view_count: 17,
          price: 4.99,
          shipping_cost: 3.99,
          description: 'A book about thinning air',
          approved: true,
        },
        {
          user_id: 6,
          active: true,
          condition_id: 1,
          category_id: 3,
          sub_category_id: 6,
          name: 'Almost Paradise',
          inventory: 1,
          dimensions: '626 pages',
          view_count: 17,
          price: 17.17,
          shipping_cost: 3.99,
          description: "It's about am almost beautiful place",
          approved: false,
        },
        {
          user_id: 1,
          active: true,
          condition_id: 3,
          category_id: 4,
          sub_category_id: 10,
          name: 'Enter the Dragon',
          inventory: 1,
          dimensions: 'N/A',
          view_count: 20,
          price: 20.98,
          shipping_cost: 3.99,
          description:
            "Recruited by an intelligence agency, outstanding martial arts student Bruce Lee participates in a brutal karate tournament hosted by the evil Han. Along with champions Roper and Williams, he uncovers Han's white slavery and drug trafficking ring located on a secret island fortress. In the exciting climax, hundreds of freed prisoners fight in an epic battle with Lee and Han locked in a deadly duel",
          approved: true,
        },
        {
          user_id: 4,
          active: true,
          condition_id: 1,
          category_id: 5,
          sub_category_id: 14,
          name: '24-Pack Fiji Natrual Artesian Water',
          inventory: 24,
          dimensions: '16.9 Fl Oz',
          view_count: 40,
          price: 18.85,
          shipping_cost: 5.99,
          description:
            'Perfect for quenching thirst on the go, in the office, and at events with a soft, smooth taste.',
          approved: true,
        },
        {
          user_id: 3,
          active: true,
          condition_id: 2,
          category_id: 5,
          sub_category_id: 15,
          name: '12 Large Organic California Hass Avocados',
          inventory: 12,
          dimensions: '8 oz',
          view_count: 5,
          price: 39.0,
          shipping_cost: 5.99,
          description:
            '12 large organic Hass avocados handpicked to order on a family owned and operated ranch in Carpinteria, California.',
          approved: true,
        },
        {
          user_id: 6,
          active: true,
          condition_id: 1,
          category_id: 5,
          sub_category_id: 13,
          name: 'Gerber Puffs Cereal Snack, Banana & Strawberry Apple, 8 Count',
          inventory: 8,
          dimensions: 'N/A',
          view_count: 111,
          price: 13.44,
          shipping_cost: 5.99,
          description: 'Nutritious snacks for tiny hands made with wholesome ingredients',
          approved: false,
        },
        {
          user_id: 2,
          active: true,
          condition_id: 4,
          category_id: 4,
          sub_category_id: 11,
          name: 'King of Thieves',
          inventory: 2,
          dimensions: 'N/A',
          view_count: 321,
          price: 9.99,
          shipping_cost: 3.99,
          description:
            'Based on infamous true events, a famouse theif, Brian Reader (Sir Michael Caine), pulls together a band of misfit criminals to plot the biggest bank heist in British History.',
          approved: true,
        },
        {
          user_id: 3,
          active: true,
          condition_id: 2,
          category_id: 4,
          sub_category_id: 12,
          name: 'Once Upon A Deadpool',
          inventory: 1,
          dimensions: 'N/A',
          view_count: 1,
          price: 14.99,
          shipping_cost: 3.99,
          description:
            'Everyones favorite disreputable Super Hero returns with a twist on Deadpool 2 that the whole gang can enjoy.',
          approved: true,
        },
        {
          user_id: 6,
          active: true,
          condition_id: 5,
          category_id: 2,
          sub_category_id: 8,
          name: "Haggar Men's Cool 18 Hidden Expandable-Waist Plain-Front Pant",
          inventory: 5,
          dimensions: '29x30',
          view_count: 17,
          price: 68.47,
          shipping_cost: 6.99,
          description: 'No-iron dress pant with flat front and expendable waist.',
          approved: true,
        },
        {
          //item #20
          user_id: 3,
          active: true,
          condition_id: 1,
          category_id: 1,
          sub_category_id: 7,
          name: 'JBL Bar 5.1 4K Ultra HD 5.1-Channel Soundbar with True Wireless Surround Speakers',
          inventory: 1,
          dimensions: '5 3-inch speakers and 1 10-inch subwoofer',
          view_count: 1001,
          price: 524.0,
          shipping_cost: 5.99,
          description: 'Easy to connect all your 4K devices and upgrade your home entertainment to ultra HD',
          approved: true,
        },
        {
          user_id: 6,
          active: true,
          condition_id: 1,
          category_id: 3,
          sub_category_id: 9,
          name: 'Better Homes & Gardens',
          inventory: 12,
          dimensions: '120 pages',
          view_count: 5,
          price: 5.0,
          shipping_cost: 3.99,
          description: 'For a yearly subscription of $5.00, you can receive a monthly copy of our Magazine.',
          approved: false,
        },
        {
          user_id: 5,
          active: true,
          condition_id: 5,
          category_id: 2,
          sub_category_id: 4,
          name: 'COOFANDY Mens Fashion T Shirt Cotton Tee Hippie Shirts Short Sleeve Beach Yoga Top',
          inventory: 6,
          dimensions: 'XX-Large',
          view_count: 0,
          price: 27.99,
          shipping_cost: 4.99,
          description: "Hippie's final choice: Wear this Hip-Hop shirt to anywhere you like",
          approved: true,
        },
        {
          user_id: 6,
          active: true,
          condition_id: 1,
          category_id: 2,
          sub_category_id: 4,
          name: 'Next Level Apparel mens Next Level Premium Jersey Tank',
          inventory: 110,
          dimensions: 'Small',
          view_count: 99,
          price: 21.97,
          shipping_cost: 4.99,
          description:
            '100% combed ring-spun cotton high-end jersey (blended combed ring-spun cotton/polyester in heather colors)',
          approved: false,
        },
        {
          user_id: 2,
          active: true,
          condition_id: 5,
          category_id: 2,
          sub_category_id: 4,
          name: "Asvivid Women's Striped Off Shoulder Bell Sleeve Shirt Tie Knot Casual Blouses Tops",
          inventory: 8000,
          dimensions: 'Medium',
          view_count: 10,
          price: 19.99,
          shipping_cost: 4.99,
          description:
            'Elegant Sexy Off the Shoulder Style, you will never out of style for our shirt, a perfect gift for your friends, roommate and yourself.',
          approved: true,
        },
      ]);
    });
};
